#!/bin/sh
git clone https://github.com/ScienceDb/ScienceDbBackend.git /root/projects/ScienceDbBackend
cd /root/projects/ScienceDbBackend
npm install --save
node_modules/.bin/sequelize db:migrate
node_modules/.bin/sequelize db:seed:all
git clone https://github.com/ScienceDb/ScienceDbGui.git /root/projects/ScienceDbGui
cd /root/projects/ScienceDbGui
npm install --save
git clone https://github.com/ScienceDb/admin_gui_gen.git /root/projects/admin_gui_gen
cd /root/projects/admin_gui_gen
npm install --save
npm install -g .
git clone https://github.com/ScienceDb/express_route_gen_js.git /root/projects/express_route_gen_js
cd /root/projects/express_route_gen_js
npm install --save
npm install -g .
