FROM node:14.4.0-alpine

RUN apk update && \
 apk add git && apk add bash && \
 npm install -g github:ScienceDb/graphql-server-model-codegen.git#latest-stable && \
 npm install -g github:ScienceDb/single-page-app-codegen.git#latest-stable

ENTRYPOINT ["/bin/bash"]
